spring:
  application:
    name: waa_lab5
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/waa_lab5
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
